# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/testquarto',
                'doc_host': 'https://jph00.github.io',
                'git_url': 'https://github.com/jph00/testquarto',
                'lib_path': 'testquarto'},
  'syms': {'testquarto.core': {'testquarto.core.foo': ('core.html#foo', 'testquarto/core.py')}}}